### ISSUE TITLE
Can't push to custom repository

### ISSUE THREAD

**Issue by ghost** [felixfbecker/semantic-release-docker#30]
Hello! I'm trying to publish to a private registry using the following .releaserc.yml.

```
---
repositoryUrl: https://github.company.net/Company/semrel.git
verifyConditions:
- "@semantic-release/github"
- - semantic-release-docker
  - registryUrl:
    - dtr.aws.e1.company.net
publish:
- "@semantic-release/github"
- - semantic-release-docker
  - name:
    - sre/semrel
githubUrl: https://github.company.net
githubApiPathPrefix: "/api/v3"
prepare: false
```
This config successfully:

- Publishes to GitHub Enterprise
- Verifies conditions for semantic-release-docker against private registry
- Passes `- name` parameter to semantic-release-docker in the publish stage

My issue is that the publish stage attempts to push to `docker.io/sre/semrel`, rather than using the private registry. I would expect publish to push to `dtr.aws.e1.company.net/sre/semrel` instead.

I am running the latest versions of [semantic-release](https://github.com/semantic-release/semantic-release/releases/tag/v15.13.8) and [semantic-release-docker](https://github.com/felixfbecker/semantic-release-docker/releases/tag/v2.2.0).
